# Generated by Django 2.2 on 2020-12-08 09:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201207_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecolumn',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/%Y%m%d'),
        ),
    ]
